### ISSUE TITLE
for what is that?

### ISSUE THREAD

**Issue by JokersCat** [Mewzax/Checky-Free#1]
So for what would you use this?

**Comment by Mewzax** [comment]
> 

because you can check faster discord invites and save the ones with a correct number of ppl (some ppl need to be on a lot of server with some members but not too many) check https://github.com/Mewzax/NitroSniperPy to understand better

**Comment by JokersCat** [comment]
Ah okay 👍

**Comment by Mewzax** [comment]
> Ah okay 👍 But is not kinda useless when you can use disboard to find servers. But anyways cool project 😊

Sometimes you have invites and you need to check them 🤷
but i will try to make a disboard/top.gg scraper also

**Comment by JokersCat** [comment]
Nice 👍

**Comment by Mewzax** [comment]
> Ah okay 👍 But is not kinda useless when you can use disboard to find servers. But anyways cool project 😊

i made a top gg scraper if you want

**Comment by Mewzax** [comment]
https://github.com/Mewzax/TopGG-Scraper
